version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nest-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=nest_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-api-app
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      # Use the SERVICE NAME 'db' and internal port 5432
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/my_db?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: